search_space:
  stages: [1, 2, 3]
  conv_types: ["DWSepConv", "MBConv", "DpConv", "SeSepConv", "SeDpConv"]
  kernel_sizes: [3, 5]
  strides: [1, 2]
  skip_connection: [True, False]
  activations: ["ReLU6", "Swish"]
  expansions: [1, 2]
  channels: [8, 16]
  has_se: [True, False]
  se_ratios: [0, 0.25]
  blocks_per_stage: [1]
  quantization_modes: ["none"]  # 新增量化选项
  
constraints:
  max_macs: 200e6
  min_macs: 2e4
  max_sram: 2000e3
  max_params: 5e6
  max_peak_memory: 8e6
  max_latency: 50  # 单位为毫秒
